pointers: pointers.o
	g++ -Wall -std=c++17 -g -o pointers pointers.o

pointers.o: pointers.cpp
	g++ -Wno-unused-but-set-variable -Wno-unused-local-typedefs -Wno-unused-variable -Wall -std=c++17 -g -c pointers.cpp
